<a href="https://colab.research.google.com/github/Suraj-Kumar09/EDA_For_AI-Machine_Learning/blob/main/Feature_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Feature Encoding

In [1]:
print("Suraj")

Suraj

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shubh0799/churn-modelling")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'churn-modelling' dataset.
Path to dataset files: /kaggle/input/churn-modelling

In [6]:
import os
os.listdir(path)

['Churn_Modelling.csv']

In [7]:
df = pd.read_csv('/kaggle/input/churn-modelling/Churn_Modelling.csv')

In [8]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

There is no null values available in dataset and all cols data is available in specific format.

In [10]:
df.describe()

         RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [12]:
df.Gender.value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

Now use some Encoding operations .

Below is some Encoding Techniq.



*   Label Encoding
*   One Hot Encoding


*   Target Encoding
*   Dummy Encoding
*   Hash Encoding

## Label Encoding

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Gender_label'] = le.fit_transform(df['Gender'].values)

In [20]:
df.head()

   RowNumber  CustomerId   Surname  ...  EstimatedSalary Exited Gender_label
0          1    15634602  Hargrave  ...        101348.88      1            0
1          2    15647311      Hill  ...        112542.58      0            0
2          3    15619304      Onio  ...        113931.57      1            0
3          4    15701354      Boni  ...         93826.63      0            0
4          5    15737888  Mitchell  ...         79084.10      0            0

[5 rows x 15 columns]

In [21]:
df.Gender_label.value_counts()

Gender_label
1    5457
0    4543
Name: count, dtype: int64

## One Hot Encoding

In [24]:
one_hot = pd.get_dummies(df['Geography'])
one_hot

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [25]:
df.head()

   RowNumber  CustomerId   Surname  ...  EstimatedSalary Exited Gender_label
0          1    15634602  Hargrave  ...        101348.88      1            0
1          2    15647311      Hill  ...        112542.58      0            0
2          3    15619304      Onio  ...        113931.57      1            0
3          4    15701354      Boni  ...         93826.63      0            0
4          5    15737888  Mitchell  ...         79084.10      0            0

[5 rows x 15 columns]

Yaha Two col Geography and Gender Chategorical hai

In [28]:
df_dummies = pd.get_dummies(df)
df_dummies.head(5)

   RowNumber  CustomerId  ...  Gender_Female  Gender_Male
0          1    15634602  ...           True        False
1          2    15647311  ...           True        False
2          3    15619304  ...           True        False
3          4    15701354  ...           True        False
4          5    15737888  ...           True        False

[5 rows x 2949 columns]

## Dummy Encoding

In [30]:
df_dummies_de = pd.get_dummies(df,drop_first=True)
df_dummies_de.head(5)

   RowNumber  CustomerId  ...  Geography_Spain  Gender_Male
0          1    15634602  ...            False        False
1          2    15647311  ...             True        False
2          3    15619304  ...            False        False
3          4    15701354  ...            False        False
4          5    15737888  ...             True        False

[5 rows x 2946 columns]

## Text Encoding

In [31]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.9/85.9 kB 2.9 MB/s eta 0:00:00
Installing collected packages: category_encoders
Successfully installed category_encoders-2.9.0

## Target Encoder

In [32]:
from category_encoders import TargetEncoder

In [34]:
df1 = pd.read_csv('/kaggle/input/churn-modelling/Churn_Modelling.csv')

In [35]:
df1.drop(columns = ["CustomerId", "RowNumber", "Surname"], axis = 1, inplace=True)

In [38]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
Gender_label       0
dtype: int64

In [39]:
encoder = TargetEncoder()

df1['Gender Encoded'] = encoder.fit_transform(df1['Gender'], df1['Exited'])

In [40]:
df1.head(5)

   CreditScore Geography  Gender  ...  EstimatedSalary  Exited  Gender Encoded
0          619    France  Female  ...        101348.88       1        0.250715
1          608     Spain  Female  ...        112542.58       0        0.250715
2          502    France  Female  ...        113931.57       1        0.250715
3          699    France  Female  ...         93826.63       0        0.250715
4          850     Spain  Female  ...         79084.10       0        0.250715

[5 rows x 12 columns]

In [41]:
df1['Gender Encoded'].value_counts()

Gender Encoded
0.164559    5457
0.250715    4543
Name: count, dtype: int64

## Benefits of TE:


Target encoding is a simple and quick encoding method that doesn't add to the dimensionality of the dataset. Therefore, it may be used as a good first try technique

## Limitations of TE:


It is dependent on the target distribution which means target encoding requires careful validation as it can be prone to overfitting.

## Hash Encoding

In [42]:
from category_encoders import HashingEncoder

In [43]:
X = df.Gender
y = df.Exited

In [44]:
ce_hash = HashingEncoder(cols = ['Gender'])
ce_hash.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      0      0      0      0      0      0      1
1         0      0      0      0      0      0      0      1
2         0      0      0      0      0      0      0      1
3         0      0      0      0      0      0      0      1
4         0      0      0      0      0      0      0      1
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      0      0      0      0      1      0      0
9996      0      0      0      0      0      1      0      0
9997      0      0      0      0      0      0      0      1
9998      0      0      0      0      0      1      0      0
9999      0      0      0      0      0      0      0      1

[10000 rows x 8 columns]

In [45]:
X = df.Geography

In [46]:
ce_hash2 = HashingEncoder(cols = ['Geography'])
ce_hash2.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7
0         0      1      0      0      0      0      0      0
1         0      0      0      1      0      0      0      0
2         0      1      0      0      0      0      0      0
3         0      1      0      0      0      0      0      0
4         0      0      0      1      0      0      0      0
...     ...    ...    ...    ...    ...    ...    ...    ...
9995      0      1      0      0      0      0      0      0
9996      0      1      0      0      0      0      0      0
9997      0      1      0      0      0      0      0      0
9998      0      0      0      0      0      0      0      1
9999      0      1      0      0      0      0      0      0

[10000 rows x 8 columns]

In [47]:
ce_hash2 = HashingEncoder(n_components=16, cols = ['Geography'])
ce_hash2.fit_transform(X,y)

      col_0  col_1  col_2  col_3  col_4  ...  col_11  col_12  col_13  col_14  col_15
0         0      1      0      0      0  ...       0       0       0       0       0
1         0      0      0      0      0  ...       1       0       0       0       0
2         0      1      0      0      0  ...       0       0       0       0       0
3         0      1      0      0      0  ...       0       0       0       0       0
4         0      0      0      0      0  ...       1       0       0       0       0
...     ...    ...    ...    ...    ...  ...     ...     ...     ...     ...     ...
9995      0      1      0      0      0  ...       0       0       0       0       0
9996      0      1      0      0      0  ...       0       0       0       0       0
9997      0      1      0      0      0  ...       0       0       0       0       0
9998      0      0      0      0      0  ...       0       0       0       0       1
9999      0      1      0      0      0  ...       0       0       0       0       0

[10000 rows x 16 columns]